SELECT NC.FO_ID,
       NC.SP_ID,
       NC.JOB_CODE,
       NC.FO_CREATE_DATE,
       NC.FO_COMPL_DATE,
       NC.MTR_ID,
       NC.MODEL_CD,
       NC.PHASE,
       NC.FORM_NBR,
       NC.PREM_ID,
       NC.DIV_NAME,
       /*NC.ADDR_LINE_1,
       NC.ADDR_LINE_2,
       NC.CITY,
       NC.STATE,
       NC.ZIP,*/
       NC.CUST_CLASS_CD,
       NC.PREM_LATITUDE,
       NC.PREM_LONGITUDE,
       NC.MR_ROUTE_TYPE,
       NC.MTR_READ_ROUTE,
       NC.PHYSICAL_RTE,
       NC.SUBAREA,
       NC.OFFICE,
       NC.DISPATCH_GROUP,
       NC.SKILL_1,
       NC.SKILL_2,
       NC.JC_Work_Type
      /* NC.OFFICE_REMARK*/
FROM RIB.dbo.AJPK_PENDING NC